#!/usr/bin/env node
// Builds web/client/js/game.gen.js: the plugin's pure sprite modules
// (pixel, character, sprites, monsters, items and whatever they require)
// wrapped as one browser ES module with a tiny CommonJS loader, so the web
// view draws heroes, weapon rigs, cosmetics and monster animations with
// exactly the terminal's code.
//
//   node web/client/sync.js          regenerate
//   node web/client/sync.js --check  exit 1 if game.gen.js is out of date
//
// Zero dependencies and no bundler: a plain text wrapper. Run it after
// changing any of those modules.
'use strict';

const fs = require('fs');
const path = require('path');

const SCRIPTS = path.join(__dirname, '..', '..', 'scripts');
const OUT = path.join(__dirname, 'js', 'game.gen.js');
const ROOTS = ['pixel', 'character', 'monsters', 'items', 'sprites'];
// Node-only and game-pane-only modules: the sprite code only touches them lazily.
const SHIMMED = new Set(['state', 'lib', 'battle', 'scene', 'loot', 'shop', 'skills', 'guild', 'bounties', 'panels', 'celebrate', 'hd', 'game']);

function collect() {
  const seen = new Map(), queue = [...ROOTS];
  while (queue.length) {
    const name = queue.shift();
    if (seen.has(name) || SHIMMED.has(name)) continue;
    const file = path.join(SCRIPTS, `${name}.js`);
    if (!fs.existsSync(file)) continue;
    const src = fs.readFileSync(file, 'utf8').replace(/^#!.*\n/, '');
    seen.set(name, src);
    for (const m of src.matchAll(/require\(\s*['"]\.\/([\w-]+)(?:\.js)?['"]\s*\)/g)) queue.push(m[1]);
  }
  return seen;
}

function build() {
  const mods = collect();
  const parts = [
    '// GENERATED by web/client/sync.js from plugins/claude-arcade/scripts. Do not edit by hand.',
    `// Modules: ${[...mods.keys()].join(', ')}. Run \`node web/client/sync.js\` after changing them.`,
    '/* eslint-disable */',
    'const defs = {};',
  ];
  for (const [name, src] of mods) parts.push(`defs['./${name}'] = function (module, exports, require) {\n${src}\n};`);
  parts.push(`
const shims = { fs: {}, os: {}, path: { basename: (p) => String(p).split(/[\\\\/]/).pop(), join: (...a) => a.join('/') }, './state': { ui: {}, UI: {} }, './lib': {} };
${[...SHIMMED].filter((n) => n !== 'state' && n !== 'lib').map((n) => `shims['./${n}'] = {};`).join('\n')}
const cache = {};
function require(name) {
  const n = name.replace(/\\.js$/, '');
  if (n in shims) return shims[n];
  if (cache[n]) return cache[n].exports;
  if (!defs[n]) throw new Error('game.gen.js: unknown module ' + name + ' (run node web/client/sync.js)');
  const m = { exports: {} };
  cache[n] = m;
  defs[n](m, m.exports, require);
  return m.exports;
}
export const X = require('./pixel');
export const C = require('./character');
export const MON = require('./monsters');
export const I = require('./items');
export const SP = require('./sprites');
export const shimUi = shims['./state'].ui;
`);
  return parts.join('\n');
}

const out = build();
if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== out) { console.error('web/client/js/game.gen.js is out of date: run node web/client/sync.js'); process.exit(1); }
  console.log('game.gen.js is up to date');
} else {
  fs.writeFileSync(OUT, out);
  console.log(`wrote ${path.relative(process.cwd(), OUT)} (${(out.length / 1024).toFixed(0)} KB)`);
}
